### ISSUE TITLE
Improve storage of visibility settings

### ISSUE THREAD

**Issue by nielslange** [Automattic/hidden-posts#17]
Currently, the visibility settings of a page or post are store as option `hidden-posts` in `wp_options`. In #8, a user requested indicating the visibility status in the admin columns. I implemented that change in #16. However, given the current storage of the visibility settings, adding sorting and filtering to the admin columns, is rather tricky.

Therefore, I propose to either move the visibility settings from `wp_options` to `wp_postmeta` or to store them in `wp_postmeta` in addition to `wp_options`.

**Thoughts**

- What are the benefits/drawbacks of storing the visibility settings only in `wp_options`?
  - A benefit might be, that hidden posts could be queries faster, as all their IDs are stored centralized.
  - A drawback is, that sorting and filtering the admin columns becomes more difficult.
- What are the benefits/drawbacks of storing the visibility settings only in `wp_postmeta`?
  - A benefit is, that sorting and filtering the admin columns becomes way easier.
  - A drawback could be, that querying hidden posts might slow down as both `wp_posts` and `wp_postmeta` need to be joined to get all visible pages/posts.
- What are the benefits/drawbacks of storing the visibility settings both in `wp_options` and `wp_postmeta`?
  - A benefit would be, that sorting and filtering the admin columns becomes way easier and that querying visible pages/posts can be executed fast.
  - A drawback is, that the visibility settings are stored redundant both in `wp_postmeta` and `wp_options`.
- When switching from `wp_options` to `wp_postmeta`, already existing records should be migrated> This might be accomplished using the hook [`upgrader_process_complete`](https://developer.wordpress.org/reference/hooks/upgrader_process_complete/).

**Comment by rickhurst** [comment]
You've correctly identified the benefits and drawbacks of each storage method individually, and storing it in two places adds complexity/ potential confusion/ redundancy. It would be interesting to quantify the query speed difference between the two different methods on a test site with a large volume of posts. However, if I was designing it from scratch it feels to me that using `wp_postmeta` as the main point of reference, then duplicating to `wp_options` for a quick lookup of all hidden posts makes sense.

**Comment by nielslange** [comment]
To test my assumption, I created the following test case:

- Create 50 posts
- Mark 10 posts as hidden
- Store the visibility settings in `wp_options` and measure the query performance
- Store the visibility settings in `wp_postmeta` and measure the query performance

These are the results:

<img width="1216" alt="Screenshot 2021-03-14 at 11 13 55" src="https://user-images.githubusercontent.com/3323310/111057243-811de100-84b8-11eb-9f82-789b7088d414.png">

<img width="1217" alt="Screenshot 2021-03-14 at 11 15 14" src="https://user-images.githubusercontent.com/3323310/111057245-83803b00-84b8-11eb-801b-3b0891a3b5ec.png">

I run each of these queries 10 times and the test result remains consistent. Looking at these two results clearly shows that the `wp_options` query runs almost twice as fast as the `wp_postmeta` query. 

With this in mind, I’ll keep the IDs of the hidden posts stored in `wp_options` to guarantee fast queries on the homepage. In addition, I’ll also store the IDs of the hidden posts in `wp_postmeta` to allow sorting and filtering of the admin columns. While storing data redundant is not a good idea in general, in this case, I’ll make an exception due to the performance wins.

**Comment by nielslange** [comment]
Closing this issue as mentioned in https://github.com/Automattic/hidden-posts/pull/22#issuecomment-875413188.
